### ISSUE TITLE
Feature Request Review

### ISSUE THREAD

**Issue by SidTheEngineer** [yuanh1987/jammming#5]
### Criteria 1: Objective Section  
* _Score Level:_ 4/4
* _Comment(s):_ The overall goal of the feature request is summarized from the user’s perspective in no more than 1-2 complete sentences.
 
### Criteria 2: Background Section
* _Score Level:_ 4/4
* _Comment(s):_ Good work here. You've given a solid overview and justified the reason behind why the functionality is important for the app.
 
### Criteria 3: Technical Design Section
* _Score Level:_ 4/4
* _Comment(s):_ Nice work explaining the technical details of the feature. I like that you created a new "Sample" class, the code looks great and you've set things up in there appropriately (bound methods, settings state, etc). Great job! 
 
### Criteria 4: Caveats Section
* _Score Level:_ 4/4
* _Comment(s):_ 
> However, each specific function in React should be handled by different components to clearly lay out the app structure and for debugging purpose. 

Good note here! As apps grow and get more complicated, it's important to keep the project structure clean and refactor when necessary.

Including the screenshot with how the album cover would be displayed with the play/pause button was a good addition as well.
 
### Overall Score: 16/16 🔥 
Awesome job! I really didn't see any issues here throughout the feature request. You detailed the functionality very well, included code snippets that reflected your technical design choices, and seemed to have executed effectively. 👍

**Comment by yuanh1987** [comment]
Thank you Sid!
